# Generated by Django 3.0 on 2019-12-08 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradmatchapp', '0009_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='expected_Enrollment_date',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='major',
            field=models.CharField(default='', max_length=200),
        ),
    ]
