# Generated by Django 3.0 on 2019-12-09 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradmatchapp', '0011_auto_20191208_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
