# Generated by Django 3.0 on 2019-12-09 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gradmatchapp', '0012_userprofile_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='expected_Enrollment_date',
            new_name='expected_Enroll_date',
        ),
    ]
