# Generated by Django 3.0 on 2019-12-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradmatchapp', '0013_auto_20191208_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='deadline',
            field=models.ManyToManyField(blank=True, to='gradmatchapp.Deadline'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='school',
            field=models.ManyToManyField(blank=True, to='gradmatchapp.School'),
        ),
    ]
