# Generated by Django 3.0 on 2019-12-09 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gradmatchapp', '0014_auto_20191209_0546'),
        ('gradmatchapp', '0014_auto_20191209_0507'),
    ]

    operations = [
    ]
