# Generated by Django 2.2.7 on 2019-12-02 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradmatchapp', '0002_location_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='acceptance_rate',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='school',
            name='graduation_rate',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='school',
            name='student_pop',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='school',
            name='tuition',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='school',
            name='area',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
