# Generated by Django 2.2.7 on 2019-11-14 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolsapp', '0002_remove_property_area'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Property',
            new_name='School',
        ),
    ]
